### ISSUE TITLE
Increase wait time between steps

### ISSUE THREAD

**Issue by iainelder** [iainelder/aws-root-account-creator#2]
The creator timed out waiting for the identity verification page because my bank inserted its authorization flow for AWS's test charge.

Increase the timeout to 10 minutes to give enough time to complete this.

```console
$ pipenv run python main.py
Email verification code: 811642
Traceback (most recent call last):
  File "main.py", line 33, in main
    create_root_account(driver, creds, config)
  File "main.py", line 59, in create_root_account
    confirm_identity(driver, config["identity_verification"])
  File "main.py", line 149, in confirm_identity
    wait_for_message(driver, "Confirm your identity")
  File "main.py", line 224, in wait_for_message
    WebDriverWait(driver, timeout).until(
  File "/home/isme/.local/share/virtualenvs/aws-root-account-creator-xJShw70_/lib/python3.8/site-packages/selenium/webdriver/support/wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:183:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:395:5
element.find/</<@chrome://remote/content/marionette/element.sys.mjs:134:16
```

**Comment by iainelder** [comment]
Commited c89dbe2401474c4af99e52e5dbeed22aa25ecb21 to address this. I'll know for sure after passing the bank authorization flow again.
