### ISSUE TITLE
Fix captcha detection

### ISSUE THREAD

**Issue by iainelder** [iainelder/aws-root-account-creator#3]
The creator failed to find the captcha element.

```console
$ pipenv run python main.py
Email verification code: 849584
Traceback (most recent call last):
  File "main.py", line 35, in main
    create_root_account(driver, config)
  File "main.py", line 71, in create_root_account
    confirm_identity(driver, config["identity_verification"])
  File "main.py", line 165, in confirm_identity
    confirm_identity_by_sms(driver, info)
  File "main.py", line 176, in confirm_identity_by_sms
    set_captcha_guess(driver, solve_captcha(extract_canvas_captcha(driver)))
  File "main.py", line 118, in extract_canvas_captcha
    canvas = driver.find_element(By.ID, "captchaCanvas")
  File "/home/isme/.local/share/virtualenvs/aws-root-account-creator-xJShw70_/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 740, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "/home/isme/.local/share/virtualenvs/aws-root-account-creator-xJShw70_/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 346, in execute
    self.error_handler.check_response(response)
  File "/home/isme/.local/share/virtualenvs/aws-root-account-creator-xJShw70_/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id="captchaCanvas"]; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:183:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:395:5
element.find/</<@chrome://remote/content/marionette/element.sys.mjs:134:16
```

It doesn't seem to be a timing problem. The debugger shows that this time the captcha is an `img` element.

```text
ipdb> driver.find_element(By.ID, "captchaCanvas")
*** selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id="captchaCanvas"]; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:183:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:395:5
element.find/</<@chrome://remote/content/marionette/element.sys.mjs:134:16

ipdb> driver.find_element(By.XPATH, "//canvas")
*** selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //canvas; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:183:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:395:5
element.find/</<@chrome://remote/content/marionette/element.sys.mjs:134:16

ipdb> driver.find_element(By.XPATH("//img[@alt='captcha']"))
*** TypeError: 'str' object is not callable
ipdb> driver.find_element(By.XPATH, "//img[@alt='captcha']")
<selenium.webdriver.remote.webelement.WebElement (session="e625af7c-cfa6-4930-a317-396b3b0de0ab", element="fbbf6b1d-7c3a-46d7-adc6-36619555b6ff")>
```

**Comment by iainelder** [comment]
Addressed in dbca175 and 2fea901. Now extracts the img-based captcha.
